# Generated by Django 3.2.3 on 2022-09-07 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0002_vehiclebooking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiclebooking',
            name='duration',
            field=models.DecimalField(decimal_places=1, max_digits=5),
        ),
    ]
