# Generated by Django 3.2.3 on 2022-09-07 00:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0003_alter_vehiclebooking_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclebooking',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
