# Generated by Django 3.2.3 on 2022-01-17 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_us', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='job',
            field=models.CharField(default='no job', max_length=120),
            preserve_default=False,
        ),
    ]
