# Generated by Django 3.2.3 on 2022-01-05 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_alter_message_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Callback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('received_on', models.DateTimeField(auto_now_add=True)),
                ('read', models.BooleanField(default=False)),
                ('responded', models.BooleanField(default=False)),
            ],
        ),
    ]
