# Generated by Django 3.2.3 on 2022-01-24 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0005_auto_20220124_1209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='response',
        ),
        migrations.AddField(
            model_name='messageresponse',
            name='response_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contact.message'),
        ),
    ]
