# Generated by Django 3.2.3 on 2022-01-24 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0006_auto_20220124_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messageresponse',
            name='response_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contact.message'),
        ),
    ]
