# Generated by Django 3.2.3 on 2022-02-15 22:31

import blog.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20220215_2139'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPostVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='blogs', validators=[blog.validators.validate_video_file])),
            ],
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='video',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='video',
            field=models.ManyToManyField(blank=True, to='blog.BlogPostVideo'),
        ),
    ]
