# Generated by Django 3.2.3 on 2022-02-17 11:05

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20220215_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='post_body',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
