# Generated by Django 3.2.3 on 2022-02-17 12:55

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_blogpost_post_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='post_body',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
