# Generated by Django 3.2.3 on 2022-02-17 13:12

import blog.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_blogpost_post_body'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='public',
            new_name='publish',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='image',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='header_image',
            field=models.ImageField(blank=True, null=True, upload_to='blogs/header_images'),
        ),
        migrations.AlterField(
            model_name='blogpostvideo',
            name='video',
            field=models.FileField(upload_to='blogs/videos', validators=[blog.validators.validate_video_file]),
        ),
        migrations.DeleteModel(
            name='BlogPostImage',
        ),
    ]
