# Generated by Django 3.2.3 on 2022-02-17 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20220217_1312'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpostvideo',
            name='filetype',
            field=models.CharField(default='mp4', max_length=24),
            preserve_default=False,
        ),
    ]
