# Generated by Django 3.2.3 on 2022-02-17 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_blogpostvideo_filetype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpostvideo',
            name='filetype',
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
    ]
