# Generated by Django 3.2.3 on 2022-02-18 16:00

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_alter_blogpostvideo_filetype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='post_body',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='some info'),
            preserve_default=False,
        ),
    ]
