# Generated by Django 3.2.3 on 2022-02-18 17:14

import blog.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_alter_blogpost_post_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpostvideo',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='blogs/videos', validators=[blog.validators.validate_video_file]),
        ),
    ]
