# Generated by Django 3.2.3 on 2022-03-27 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_blogpostcomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpostcomment',
            name='blogpost',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.blogpost'),
        ),
    ]
