# Generated by Django 3.2.3 on 2022-03-27 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_blogpostlike'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogPostLike',
        ),
    ]
