# Generated by Django 3.2.3 on 2021-06-28 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_site_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advert',
            name='url',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.site_page'),
        ),
    ]
