# Generated by Django 3.2.3 on 2022-02-28 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_advert_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Site_Page',
            new_name='SitePage',
        ),
    ]
