# Generated by Django 3.2.3 on 2022-05-12 14:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0003_alter_product_fitting_cost'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(blank=True, null=True)),
                ('stars', models.IntegerField(choices=[('', 'Select'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default='')),
                ('review', models.TextField()),
                ('anon', models.BooleanField(default=False)),
                ('read', models.BooleanField(default=False)),
                ('authorised', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ProductReviewImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='reviews')),
            ],
        ),
        migrations.DeleteModel(
            name='ProductAttributeBase',
        ),
        migrations.AddField(
            model_name='productreview',
            name='image',
            field=models.ManyToManyField(blank=True, to='shop.ProductReviewImage'),
        ),
        migrations.AddField(
            model_name='productreview',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product'),
        ),
        migrations.AddField(
            model_name='productreview',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='product_reviews', to=settings.AUTH_USER_MODEL),
        ),
    ]
