# Generated by Django 3.2.3 on 2022-01-10 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testimonials', '0004_auto_20220110_0002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewimages',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
