# Generated by Django 3.2.3 on 2022-01-10 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testimonials', '0006_auto_20220110_1222'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ReviewImages',
            new_name='ReviewImage',
        ),
    ]
