# Generated by Django 3.2.3 on 2022-01-12 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testimonials', '0007_rename_reviewimages_reviewimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='stars',
            field=models.IntegerField(choices=[('', 'Select'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=''),
        ),
        migrations.AlterField(
            model_name='reviewimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='reviews'),
        ),
    ]
