# Generated by Django 3.2.3 on 2022-01-14 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testimonials', '0008_auto_20220112_1025'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='updated_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
