# Generated by Django 3.2.3 on 2022-01-14 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testimonials', '0009_review_updated_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='read',
            field=models.BooleanField(default=False),
        ),
    ]
